#!/bin/bash

# Get the Python script file name from the environment variable
python_script="$PYFILE"

# Check if the Python script exists
if [ -f "$python_script" ]; then
    # Run the Python script
    python3 "$python_script"
else
    echo "Error: Python script not found!"
fi

